### ISSUE TITLE
cmake issue

### ISSUE THREAD

**Issue by cyrus104** [argilo/gr-dsd#12]
I'm looking for some help to understand why this is failing to compile.

~/pybombs/src/gr-dsd/build$ cmake ..
-- Boost version: 1.58.0
  File "<string>", line 3
    print sysconfig.get_python_lib(plat_specific=True, prefix='')
                  ^
SyntaxError: invalid syntax
CMake Error at cmake/Modules/GrPython.cmake:103 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:25 (include)
  swig/CMakeLists.txt:28 (include)

Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
  File "<string>", line 3
    print sysconfig.get_python_lib(plat_specific=True, prefix='')
                  ^
SyntaxError: invalid syntax
CMake Error at cmake/Modules/GrPython.cmake:103 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  python/CMakeLists.txt:23 (include)

Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Error at cmake/Modules/GrPython.cmake:115 (add_custom_target):
  add_custom_target cannot create target "ALL" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory "/home/dader/pybombs/src/gr-dsd/swig".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/Modules/GrPython.cmake:214 (GR_UNIQUE_TARGET)
  python/CMakeLists.txt:31 (GR_PYTHON_INSTALL)

-- Found LibSndFile: /usr/lib/arm-linux-gnueabihf/libsndfile.so
-- Configuring incomplete, errors occurred!
See also "/home/dader/pybombs/src/gr-dsd/CMakeFiles/CMakeOutput.log".

**Comment by argilo** [comment]
This should be fixed now. Let me know if you have any trouble building the latest version.

**Comment by cafeclimber** [comment]
Can I ask what was done to fix this? I'm having the same issue with gr-eventstream

**Comment by argilo** [comment]
@cafeclimber I used gr_modtool to create a fresh module, then moved my code into that.

**Comment by argilo** [comment]
Here's the commit: https://github.com/argilo/gr-dsd/commit/23d29f6808207d5aec96aea9ac9349ed6eb0d6ef
