### ISSUE TITLE
error: 'make_block_sptr' is not a member of 'gnuradio'

### ISSUE THREAD

**Issue by strijar** [argilo/gr-dsd#23]
Hello!
Can't compile, any advice?

GNU Radio 3.10.5.1
GCC 12.2.1

> /home/master/SDR/gr-dsd/lib/dsd_block_ff_impl.cc: In static member function 'static gr::dsd::dsd_block_ff::sptr gr::dsd::dsd_block_ff::make(gr::dsd::dsd_frame_mode, gr::dsd::dsd_modulation_optimizations, int, bool, int)':
> /home/master/SDR/gr-dsd/lib/dsd_block_ff_impl.cc:31:22: error: 'make_block_sptr' is not a member of 'gnuradio'
>    31 |     return gnuradio::make_block_sptr<dsd_block_ff_impl>(
>       |                      ^~~~~~~~~~~~~~~
> /home/master/SDR/gr-dsd/lib/dsd_block_ff_impl.cc:31:55: error: expected primary-expression before '>' token
>    31 |     return gnuradio::make_block_sptr<dsd_block_ff_impl>(
>       |                                                       ^
> make[2]: *** [lib/CMakeFiles/gnuradio-dsd.dir/build.make:76: lib/CMakeFiles/gnuradio-dsd.dir/dsd_block_ff_impl.cc.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:271: lib/CMakeFiles/gnuradio-dsd.dir/all] Error 2
>

**Comment by argilo** [comment]
Do you have multiple versions of GNU Radio installed? If so, you'll need to uninstall the older ones so that the correct version is chosen during compilation of gr-dsd.
